### Get User
GET http://localhost:8080/user/7
Accept: application/json

### Get all Users
GET http://localhost:8080/user/all
Accept: application/json

### Update User
POST http://localhost:8080/user/7
Accept: application/json
Content-Type: application/json

{
  "id": 7,
  "userName": "Daenerys Targaryen",
  "email": "daenerys@gmail.com",
  "password": "notsecured",
  "status": "SUSPENDED"
}

### Get Catalog Metadata
GET http://localhost:8080/catalog/metadata
Accept: application/json


### Get Catalog Artists
GET http://localhost:8080/catalog/artists
Accept: application/json


### Get Song Lyrics
GET http://localhost:8080/catalog/Michael%20Jackson/smooth%20criminal/lyrics
Accept: application/json
